Test Sandbox Project/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duplicate_Key__c</fullName>
        <externalId>true</externalId>
        <label>Duplicate Key</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Sandbox Project/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Created_By__c</fullName>
        <label>Case Created By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duplicate_Key__c</fullName>
        <label>Duplicate Key</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Migration__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Migration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tiket_ID__c</fullName>
        <externalId>true</externalId>
        <label>Tiket ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

Test Sandbox Project/src/classes/ObjCaseMigration_test.cls
@isTest(seeAllData=true)
public class ObjCaseMigration_test {
    static testmethod void cases(){
        Test.startTest();
        
        Account acc2 = [select id, duplicate_key__C, personcontactid,contact__c from account where duplicate_key__C != null limit 1];
       
        Case cs3 = new Case();
        cs3.Duplicate_Key__c = acc2.Duplicate_Key__c;
        cs3.Tiket_ID__c = '1234';
        cs3.origin = 'Web';
        cs3.status = 'New';
        cs3.case_created_by__c = 'Customer';
        cs3.Migration__c = true;
        cs3.Subject = 'Kendala Akun';
        cs3.Description = 'Masalah akun';        
        
        insert cs3;
        
        Test.stopTest();
    }
    
}