Test Sandbox Project/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duplicate_Key__c</fullName>
        <externalId>true</externalId>
        <label>Duplicate Key</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Sandbox Project/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Created_By__c</fullName>
        <label>Case Created By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Mobile__c</fullName>
        <label>Case Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duplicate_Key__c</fullName>
        <label>Duplicate Key</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email_Guest__c</fullName>
        <label>Email Guest</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Guest__c</fullName>
        <label>Is Guest</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Migration__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Migration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Need_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Call</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

Test Sandbox Project/src/classes/ObjCase_test4.cls
@isTest(seeAllData=true)
public class ObjCase_test4 {
    static testmethod void casetest4() {
        Test.startTest();
        Account acc = new Account();
        acc.firstname = 'budi';
        acc.lastname = 'idub';
        acc.duplicate_key__c = 'ketanitem@gmail.com';
        acc.personemail = 'ketanitem@gmail.com';
        acc.recordtypeid = label.recordtype_id;
        insert acc;
		
		Contact con = new Contact();
        con.firstname = 'budi';
        con.lastname = 'idub';
        con.email = 'ketanijo@gmail.com';
        insert con;
        
        Case cs = new Case();
        cs.accountid = acc.id;
        cs.origin = 'Web';
        cs.status = 'New';
        cs.case_created_by__c = 'Customer';
        
        Case cs1 = new Case();
        cs1.Is_Guest__c = 'Yes';
        cs1.Full_Name__c = 'ali oncom';
        cs1.Email_Guest__c = 'sodasusu@gmail.com';
        cs1.origin = 'Web';
        cs1.status = 'New';
        cs1.case_created_by__c = 'Customer';
        
        Case cs2 = new Case();
        cs2.contactid = con.id;
        cs2.origin = 'Web';
        cs2.status = 'New';
        cs2.case_created_by__c = 'Customer';
        
        Account acc2 = [select id, duplicate_key__C, personcontactid,contact__c from account where duplicate_key__C != null limit 1];
       
        Case cs3 = new Case();
        cs3.AccountId = acc2.id;
        cs3.ContactId = acc2.PersonContactId;
        cs3.Contact__c = acc2.Contact__c;
        cs3.Need_Call__c = true;
        cs3.Case_Mobile__c = '62666454444';
        cs3.origin = 'Web';
        cs3.status = 'New';
        cs3.case_created_by__c = 'Customer';
        cs3.Migration__c = false;
        cs3.Subject = 'Kendala Akun';
        cs3.Description = 'Masalah akun';
        
        insert cs3;
        Test.stopTest();
    }
}