Test Sandbox Project/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duplicate_Key__c</fullName>
        <externalId>true</externalId>
        <label>Duplicate Key</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Sandbox Project/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Created_By__c</fullName>
        <label>Case Created By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duplicate_Key__c</fullName>
        <label>Duplicate Key</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Migration__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Migration</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

Test Sandbox Project/src/classes/TriggerCase_test3.cls
@isTest(seeAllData=true)
private class TriggerCase_test3 {
	static testmethod void cases7(){
        
        Account acc2 = [select id, duplicate_key__C, personcontactid,contact__c from account where duplicate_key__C != null limit 1];
        
        Case cs4 = new Case();
        cs4.Duplicate_Key__c = acc2.Duplicate_Key__c;
        cs4.origin = 'Web';
        cs4.status = 'New';
        cs4.case_created_by__c = 'Customer';
        cs4.Migration__c = true;
        cs4.Subject = 'testing';
        cs4.Description = 'topads tidak terkirim';
        
        Test.startTest();
        insert cs4;
        Case cs5 = cs4.clone(false);
        cs5.Description = 'iklan belum muncul';
        insert cs5;
        Case cs6 = cs4.clone(false);
        cs6.Description = 'produk tidak aktif';
        insert cs6;
        Case cs7 = cs4.clone(false);
        cs7.Description = 'kredit belum bertambah';
        insert cs7;
        Case cs8 = cs4.clone(false);
        cs8.Description = 'admin toko';
        insert cs8;
        Case cs9 = cs4.clone(false);
        cs9.Description = 'etalase produk hilang';
        insert cs9;
        Case cs10 = cs4.clone(false);
        cs10.Description = 'etalase hilang';
        insert cs10;
        
        Test.stopTest();
    }
    
    static testmethod void cases8(){
        
        Account acc2 = [select id, duplicate_key__C, personcontactid,contact__c from account where duplicate_key__C != null limit 1];
        
        Case cs4 = new Case();
        cs4.Duplicate_Key__c = acc2.Duplicate_Key__c;
        cs4.origin = 'Web';
        cs4.status = 'New';
        cs4.case_created_by__c = 'Customer';
        cs4.Migration__c = true;
        cs4.Subject = 'testing';
        cs4.Description = 'free return produk tidak aktif';
        
        Test.startTest();
        insert cs4;
        Case cs5 = cs4.clone(false);
        cs5.Description = 'free return berhenti berlangganan';
        insert cs5;
        Case cs6 = cs4.clone(false);
        cs6.Description = 'etalase produk tidak muncul';
        insert cs6;
        Case cs7 = cs4.clone(false);
        cs7.Description = 'gambar produk';
        insert cs7;
        Case cs8 = cs4.clone(false);
        cs8.Description = 'gagal upload produk';
        insert cs8;
        Case cs9 = cs4.clone(false);
        cs9.Description = 'produk dihapus';
        insert cs9;
        Case cs10 = cs4.clone(false);
        cs10.Description = 'pengawasan';
        insert cs10;
        
        Test.stopTest();
    }
    
    static testmethod void cases9(){
        
        Account acc2 = [select id, duplicate_key__C, personcontactid,contact__c from account where duplicate_key__C != null limit 1];
        
        Case cs4 = new Case();
        cs4.Duplicate_Key__c = acc2.Duplicate_Key__c;
        cs4.origin = 'Web';
        cs4.status = 'New';
        cs4.case_created_by__c = 'Customer';
        cs4.Migration__c = true;
        cs4.Subject = 'testing';
        cs4.Description = 'kolom pencarian';
        
        Test.startTest();
        insert cs4;
        Case cs5 = cs4.clone(false);
        cs5.Description = 'presentase transaksi';
        insert cs5;
        Case cs6 = cs4.clone(false);
        cs6.Description = 'poin reputasi';
        insert cs6;
        Case cs7 = cs4.clone(false);
        cs7.Description = 'produk terjual';
        insert cs7;
        Case cs8 = cs4.clone(false);
        cs8.Description = 'transaksi berhasil statistik';
        insert cs8;
        Case cs9 = cs4.clone(false);
        cs9.Description = 'smiley';
        insert cs9;
        Case cs10 = cs4.clone(false);
        cs10.Description = 'kota asal belum tersedia';
        insert cs10;
        
        Test.stopTest();
    }
}