Test Sandbox Project/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Duplicate_Key__c</fullName>
        <externalId>true</externalId>
        <label>Duplicate Key</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Sandbox Project/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Created_By__c</fullName>
        <label>Case Created By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duplicate_Key__c</fullName>
        <label>Duplicate Key</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

Test Sandbox Project/src/classes/CallWS_Test.cls
@isTest(seeAllData=true)
private class CallWS_Test {
    static testMethod void WS() {
        Account acc = new Account();
        acc.firstname = 'budi';
        acc.lastname = 'idub';
        acc.duplicate_key__c = 'sodasusu@gmail.com';
        acc.personemail = 'sodasusu@gmail.com';
        acc.recordtypeid = label.recordtype_id;
        insert acc;
        
        Case cs = new Case();
        cs.accountid = acc.id;
        cs.origin = 'Web';
        cs.status = 'New';
        cs.case_created_by__c = 'Customer';
        insert cs;
        Test.startTest();
        CallWS.getData(label.url_read, cs.id, acc.id);
        Test.stopTest();
    }
}