Test Sandbox Project/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Duplicate_Key__c</fullName>
        <externalId>true</externalId>
        <label>Duplicate Key</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Sandbox Project/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_No__c</fullName>
        <externalId>true</externalId>
        <label>Invoice No</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Konfirmasi Pembayaran</fullName>
                </value>
                <value>
                    <fullName>Verifikasi Pembayaran</fullName>
                </value>
                <value>
                    <fullName>Dalam Proses</fullName>
                </value>
                <value>
                    <fullName>Dalam Pengiriman</fullName>
                </value>
                <value>
                    <fullName>Transaksi Terkirim</fullName>
                </value>
                <value>
                    <fullName>Transaksi Selesai</fullName>
                </value>
                <value>
                    <fullName>Transaksi Dibatalkan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV{00}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Sandbox Project/src/classes/triggerinvoice_test.cls
@isTest(seeAllData=true)
private class triggerinvoice_test {
    static testmethod void update_customer(){
        Account acc = new Account();
        acc.FirstName = 'Wilhan';
        acc.LastName = 'Robin';
        acc.RecordTypeId = label.recordtype_id;
        acc.PersonEmail = 'taufik.susanto@mii.co.id';
        acc.Duplicate_Key__c = 'taufik.susanto@mii.co.id';
        insert acc;
        Invoice__c invc = new Invoice__c();
        invc.Account__c = acc.id;
        invc.Invoice_Date__c = date.today();
        invc.Invoice_No__c = 'INV/XXXXX';
        invc.Invoice_Status__c = 'Finished';
        insert invc;
    }	
}