Test Sandbox Project/src/objects/Agent_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Attendance_Refresh__c</fullName>
        <defaultValue>false</defaultValue>
        <description>untuk hitung ulang</description>
        <label>Attendance Refresh</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSAT_Refresh__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CSAT Refresh</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_Date__c</fullName>
        <label>Document Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hold_Time_Refresh__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hold Time Refresh</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Productivity_Refresh__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Productivity Refresh</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QA_Refresh__c</fullName>
        <defaultValue>false</defaultValue>
        <label>QA Refresh</label>
        <type>Checkbox</type>
    </fields>
    <label>Agent Achievement</label>
    <nameField>
        <label>Agent Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agent Achievement</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Test Sandbox Project/src/objects/Agent_Response_Case__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Agent Response Case</relationshipLabel>
        <relationshipName>Agent_Response_Case</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Survey_Taken__c</fullName>
        <label>Date Survey Taken</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent_Response_Case</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agent Response Case</label>
    <nameField>
        <displayFormat>ARC-{0000000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Response Case</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Sandbox Project/src/objects/Case_Chat__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Chat</relationshipLabel>
        <relationshipName>Case_Chat</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Document_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Document Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Messages2__c</fullName>
        <label>Messages</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Chat</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Chat</label>
    <nameField>
        <label>Case Chat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Chat</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Sandbox Project/src/objects/Response__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Response</label>
    <nameField>
        <displayFormat>RES-{0000000}</displayFormat>
        <label>Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Test Sandbox Project/src/classes/Test_AgentAchievement.cls
@isTest(seeAllData=true)
private class Test_AgentAchievement{

    static testMethod void myTest() {
        Test.startTest();

        case cs = [SELECT id FROM Case 
            where account.personcontact.email != NULL
        limit 1];

        // insert Case Chat
        Case_chat__c cc = new Case_chat__c();
        cc.user__c = UserInfo.getUserId();
        cc.Document_Date__c = Date.newInstance(2017, 1, 31);
        cc.case__c = cs.id;
        cc.messages2__c = 'testing';
        cc.email__c = 'taufik.susanto@mii.co.id';
        insert cc;
        cc.Document_Date__c = Date.newInstance(2017, 1, 31);
        update cc;

        // insert task
        Task tsk = new Task();
        tsk.ActivityDate = Date.newInstance(2017, 1, 1);
        tsk.Start_Call__c = Date.newInstance(2017, 1, 1); //System.Now();
        tsk.End_Call__c = Date.newInstance(2017, 1, 2); //System.Now();
        insert tsk;

        // insert survey
        Agent_Response_Case__c tsk2 = new Agent_Response_Case__c();
        
        tsk2.User_Agent__c = UserInfo.getUserId();
        tsk2.Date_Survey_Taken__c = Date.newInstance(2017, 1, 31);
        tsk2.Case__c = cs.id;
        tsk2.Response__c = 1;
        insert tsk2;

        Agent_Achievement__c agst = new Agent_Achievement__c();
        agst.Name = 'test';
        agst.Document_Date__c = Date.newInstance(2017, 1, 1);        

        insert agst;
        
        agst.Attendance_Refresh__c = TRUE;
        agst.CSAT_Refresh__c = TRUE;
        agst.Hold_Time_Refresh__c = TRUE;
        agst.Productivity_Refresh__c = TRUE;
        agst.QA_Refresh__c = TRUE;

        update agst;
        
        Test.stopTest();
    }
}