Test Sandbox Project/src/objects/Agent_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Attendance_Refresh__c</fullName>
        <defaultValue>false</defaultValue>
        <description>untuk hitung ulang</description>
        <label>Attendance Refresh</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSAT_Refresh__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CSAT Refresh</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_Date__c</fullName>
        <label>Document Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hold_Time_Refresh__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hold Time Refresh</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Productivity_Refresh__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Productivity Refresh</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QA_Refresh__c</fullName>
        <defaultValue>false</defaultValue>
        <label>QA Refresh</label>
        <type>Checkbox</type>
    </fields>
    <label>Agent Achievement</label>
    <nameField>
        <label>Agent Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agent Achievement</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Test Sandbox Project/src/classes/SchUpdateAG.cls
// Update Agent Achivement every day
Global class SchUpdateAG implements Schedulable {

  public static String CRON_EXP = '0 0 0 3 9 ? 2022';

    Global void execute(SchedulableContext ctx) {
        
        Date ThisDay = date.today();
        string q = '';
        if (ThisDay.day() == 1)
            //list<Agent_Achievement__c> ag2 = [
            q = 'SELECT id, OwnerId, Attendance_Refresh__c, CSAT_Refresh__c, Hold_Time_Refresh__c, Productivity_Refresh__c, QA_Refresh__c FROM Agent_Achievement__c WHERE Document_Date__c = LAST_MONTH';
        else 
            q = 'SELECT id, OwnerId, Attendance_Refresh__c, CSAT_Refresh__c, Hold_Time_Refresh__c, Productivity_Refresh__c, QA_Refresh__cFROM Agent_Achievement__c WHERE Document_Date__c = THIS_MONTH';


        UpdateAGBatch UserAgent = new UpdateAGBatch(q);
        Database.executeBatch(UserAgent, 1);

        
    } // end execute
} // end class