Test Sandbox Project/src/objects/Case_Chat__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Chat</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Chat</label>
    <nameField>
        <label>Case Chat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Chat</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Sandbox Project/src/classes/ClassCase_Test.cls
@isTest(seeAllData=true)
private class ClassCase_Test {
    static testmethod void sendemail(){
        Case cs = [select id from case where accountid != null and account.personemail!=null limit 1];
        Test.startTest();
        class_case.sendEmail(cs.id);
        Test.stopTest();
    }
    static testmethod void sendemail2(){
        //Case cs = [select id from case where accountid != null and account.personemail!=null limit 1];
        Case_Chat__c cc = [select id from case_chat__c where user__c!=null limit 1];
        Test.startTest();
        class_case.sendEmailCaseChat(cc.id);
        Test.stopTest();
    }
}