Test Sandbox Project/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_SubCategory_1__c</fullName>
        <label>Sub Category 1</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Kendala Login</fullName>
                </value>
                <value>
                    <fullName>Akun dihack</fullName>
                </value>
                <value>
                    <fullName>Akun diblokir</fullName>
                </value>
                <value>
                    <fullName>Laporan phishing</fullName>
                </value>
                <value>
                    <fullName>Laporan penipuan</fullName>
                </value>
                <value>
                    <fullName>Kendala teknis akun</fullName>
                </value>
                <value>
                    <fullName>Gold Merchant</fullName>
                </value>
                <value>
                    <fullName>TopAds</fullName>
                </value>
                <value>
                    <fullName>Admin Toko</fullName>
                </value>
                <value>
                    <fullName>Etalase</fullName>
                </value>
                <value>
                    <fullName>Free Return</fullName>
                </value>
                <value>
                    <fullName>Produk</fullName>
                </value>
                <value>
                    <fullName>Reputasi Toko</fullName>
                </value>
                <value>
                    <fullName>Statistik Toko</fullName>
                </value>
                <value>
                    <fullName>Pengaturan Pengiriman</fullName>
                </value>
                <value>
                    <fullName>Gagal checkout dengan Credit Card</fullName>
                </value>
                <value>
                    <fullName>Gagal checkout dengan instant payment lainnya</fullName>
                </value>
                <value>
                    <fullName>Dana belum masuk rekening</fullName>
                </value>
                <value>
                    <fullName>Salah data saat tarik dana</fullName>
                </value>
                <value>
                    <fullName>Dana WD kembali ke saldo Tokopedia</fullName>
                </value>
                <value>
                    <fullName>Tujuan pengiriman belum tersedia</fullName>
                </value>
                <value>
                    <fullName>Promo Marketplace</fullName>
                </value>
                <value>
                    <fullName>Promo Digital</fullName>
                </value>
                <value>
                    <fullName>Promo Tiket kereta</fullName>
                </value>
                <value>
                    <fullName>Pencarian tiket gagal</fullName>
                </value>
                <value>
                    <fullName>Pembelian tiket gagal dan dana terpotong</fullName>
                </value>
                <value>
                    <fullName>Data pada kode booking salah</fullName>
                </value>
                <value>
                    <fullName>Transaksi dengan kode voucher gagal</fullName>
                </value>
                <value>
                    <fullName>Pulsa Tidak Masuk</fullName>
                </value>
                <value>
                    <fullName>Pengisian Pulsa Selalu Gagal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Akun</fullName>
                </value>
                <value>
                    <fullName>Jualan</fullName>
                </value>
                <value>
                    <fullName>Gagal Checkout</fullName>
                </value>
                <value>
                    <fullName>Tarik Dana</fullName>
                </value>
                <value>
                    <fullName>Pengiriman</fullName>
                </value>
                <value>
                    <fullName>Promo</fullName>
                </value>
                <value>
                    <fullName>Kritik &amp; Saran</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Tiket Kereta</fullName>
                </value>
                <value>
                    <fullName>Pulsa</fullName>
                </value>
                <value>
                    <fullName>Paket Data</fullName>
                </value>
                <value>
                    <fullName>BPJS</fullName>
                </value>
                <value>
                    <fullName>PLN</fullName>
                </value>
                <value>
                    <fullName>Saldo</fullName>
                </value>
                <value>
                    <fullName>Voucher Game</fullName>
                </value>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Angsuran Kredit</fullName>
                </value>
                <value>
                    <fullName>Donasi</fullName>
                </value>
                <value>
                    <fullName>Pascabayar</fullName>
                </value>
                <value>
                    <fullName>TV Kabel</fullName>
                </value>
                <value>
                    <fullName>Telepon</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pending UNIK</fullName>
                </value>
                <value>
                    <fullName>CC Challenge</fullName>
                </value>
                <value>
                    <fullName>Pending Due</fullName>
                </value>
                <value>
                    <fullName>Waiting third party</fullName>
                </value>
                <value>
                    <fullName>Checkout State</fullName>
                </value>
                <value>
                    <fullName>Payment Confirm</fullName>
                </value>
                <value>
                    <fullName>Payment Confirmed UNIK</fullName>
                </value>
                <value>
                    <fullName>Payment Due</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category2__c</fullName>
        <label>Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_SubCategory_1__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Tidak menerima kode OTP</fullName>
                </value>
                <value>
                    <fullName>Ubah nomor Handphone</fullName>
                </value>
                <value>
                    <fullName>Lupa kata sandi</fullName>
                </value>
                <value>
                    <fullName>Belum diperpanjang</fullName>
                </value>
                <value>
                    <fullName>Belum aktif</fullName>
                </value>
                <value>
                    <fullName>Statistik</fullName>
                </value>
                <value>
                    <fullName>Badge tidak muncul</fullName>
                </value>
                <value>
                    <fullName>Kredit belum bertambah</fullName>
                </value>
                <value>
                    <fullName>Iklan belum muncul</fullName>
                </value>
                <value>
                    <fullName>Produk tidak aktif</fullName>
                </value>
                <value>
                    <fullName>Etalase hilang</fullName>
                </value>
                <value>
                    <fullName>Produk tidak muncul di etalase</fullName>
                </value>
                <value>
                    <fullName>Status produk tidak aktif</fullName>
                </value>
                <value>
                    <fullName>Berhenti berlangganan</fullName>
                </value>
                <value>
                    <fullName>Tidak muncul di etalase</fullName>
                </value>
                <value>
                    <fullName>Gambar hilang</fullName>
                </value>
                <value>
                    <fullName>Gagal upload</fullName>
                </value>
                <value>
                    <fullName>Di-banned</fullName>
                </value>
                <value>
                    <fullName>Dalam pengawasan</fullName>
                </value>
                <value>
                    <fullName>Tidak muncul di pencarian</fullName>
                </value>
                <value>
                    <fullName>Persentase transaksi berhasil</fullName>
                </value>
                <value>
                    <fullName>Jumlah reputasi tidak sesuai</fullName>
                </value>
                <value>
                    <fullName>Statistik produk terjual</fullName>
                </value>
                <value>
                    <fullName>Statistik transaksi berhasil</fullName>
                </value>
                <value>
                    <fullName>Statistik kepuasan toko</fullName>
                </value>
                <value>
                    <fullName>Kota asal belum tersedia</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Dana terdebet</fullName>
                </value>
                <value>
                    <fullName>Kartu tidak bisa digunakan</fullName>
                </value>
                <value>
                    <fullName>JNE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

Test Sandbox Project/src/objects/Spike_Ticket_Counter__c.object
<CustomObject>
    <fields>
        <fullName>Category_1__c</fullName>
        <label>Category 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_2__c</fullName>
        <label>Category 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_3__c</fullName>
        <label>Category 3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Hour_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Last Hour Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Hour_Same_Day_Threshold_Crossed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Last Hour Same Day Threshold Crossed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Same_Hour_Previous_Day_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Same Hour Previous Day Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Same_Hour_Previous_Day_Growth__c</fullName>
        <formula>IF(OR(ISNULL(Same_Hour_Previous_Day_Count__c), Same_Hour_Previous_Day_Count__c == 0), 0, ((NULLVALUE(This_Hour_Count__c, 0) - NULLVALUE(Same_Hour_Previous_Day_Count__c, 0)) / NULLVALUE(Same_Hour_Previous_Day_Count__c, 0))*100)</formula>
        <label>Same Hour Previous Day Growth</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Same_Hour_Previous_Day_Threshold_Crossed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Same Hour Previous Day Threshold Crossed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>This_Hour_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>This Hour Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>This_Hour_Growth__c</fullName>
        <formula>IF(OR(ISNULL(Last_Hour_Count__c), Last_Hour_Count__c == 0), 0, ((NULLVALUE(This_Hour_Count__c, 0) - NULLVALUE(Last_Hour_Count__c, 0)) / NULLVALUE(Last_Hour_Count__c, 0))*100)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>This Hour Growth</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Spike Ticket Counter</label>
    <nameField>
        <displayFormat>STC-{0000}</displayFormat>
        <label>Spike Ticket Counter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spike Ticket Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Sandbox Project/src/objects/Spike_Ticket_Notification_Scenerio__mdt.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category_1__c</fullName>
        <label>Category 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_2__c</fullName>
        <label>Category 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_3__c</fullName>
        <label>Category 3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Threshold__c</fullName>
        <label>Threshold %</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Last Hour Same Day</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Same Hour Previous Day</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Spike Ticket Notification Scenerio</label>
    <pluralLabel>Spike Ticket Notification Scenerios</pluralLabel>
</CustomObject>

Test Sandbox Project/src/classes/SpikeTicketCounterManager.cls
public class SpikeTicketCounterManager {
	
    public static Map<String, List<Spike_Ticket_Notification_Scenerio__mdt>> spikeTicketNotificationScenerios;
    
    static{
        spikeTicketNotificationScenerios = new Map<String, List<Spike_Ticket_Notification_Scenerio__mdt>>();
        List<Spike_Ticket_Notification_Scenerio__mdt> scenerios = [
            SELECT Category_1__c, Category_2__c, Category_3__c, Threshold__c, Type__c 
            FROM Spike_Ticket_Notification_Scenerio__mdt WHERE Active__c = true
        ]; 
        if(!scenerios.isEmpty()){
            for(Spike_Ticket_Notification_Scenerio__mdt scenerio :scenerios){
                String uniqueKey = scenerio.Category_1__c + scenerio.Category_2__c + scenerio.Category_3__c;
                if(spikeTicketNotificationScenerios.containsKey(uniqueKey)){
                    spikeTicketNotificationScenerios.get(uniqueKey).add(scenerio);
                } else {
                    spikeTicketNotificationScenerios.put(uniqueKey, new List<Spike_Ticket_Notification_Scenerio__mdt>{scenerio});
                }
            }
        }
    } 
    
    private static List<Spike_Ticket_Notification_Scenerio__mdt> getScenerios(Spike_Ticket_Counter__c stc){
        return spikeTicketNotificationScenerios.get(stc.Category_1__c + stc.Category_2__c + stc.Category_3__c);
    }
    
    public static void checkForThresholdCrossed(List<Spike_Ticket_Counter__c> counters){
        for(Spike_Ticket_Counter__c counter :counters){
            List<Spike_Ticket_Notification_Scenerio__mdt> scenerios = getScenerios(counter);
            if(scenerios != null){
                for(Spike_Ticket_Notification_Scenerio__mdt scenerio :scenerios){
                    if(scenerio.Type__c == 'Last Hour Same Day' && counter.This_Hour_Growth__c >= scenerio.Threshold__c){
                        counter.Last_Hour_Same_Day_Threshold_Crossed__c = true;
                    } else if(scenerio.Type__c == 'Same Hour Previous Day' && counter.Same_Hour_Previous_Day_Growth__c >= scenerio.Threshold__c){
                        counter.Same_Hour_Previous_Day_Threshold_Crossed__c = true; 
                    }
                }
            }
        }
    }
    
    public static void setSpikeTicketCounters(List<Case> inputCases){
        List<Case> cases = new List<Case>();
        
        Set<String> Categories1 = new Set<String>();
        Set<String> Categories2 = new Set<String>();
        Set<String> Categories3 = new Set<String>();
        
        for(Case c :inputCases){
            if(c.Category__c != null || c.Case_SubCategory_1__c != null || c.Sub_Category2__c != null){
                if(c.Category__c != null){
                    Categories1.add(c.Category__c); 
                }
                if(c.Case_SubCategory_1__c != null){
                    Categories2.add(c.Case_SubCategory_1__c);
                }
                if(c.Sub_Category2__c != null){
                    Categories3.add(c.Sub_Category2__c); 
                }
                cases.add(c);
            }
        }
        if(cases.isEmpty()){
         	return;   
        }
        DateTime thisHour = getThisHourDate();
        DateTime lastHour = getLastHourDate();
        DateTime previousDayThisHour = getPreviousDayThisHourDate();
        DateTime previousDayLastHour = getPreviousDayLastHourDate();
        
        List<Spike_Ticket_Counter__c> existingCounters = [
            SELECT Last_Hour_Count__c, This_Hour_Count__c, Same_Hour_Previous_Day_Count__c, CreatedDate, Category_1__c, Category_2__c, Category_3__c
            FROM Spike_Ticket_Counter__c
            WHERE (CreatedDate >=: lastHour OR (CreatedDate >=: previousDayLastHour AND CreatedDate <: previousDayThisHour)) 
            AND Category_1__c IN :Categories1 AND Category_2__c IN :Categories2 AND Category_3__c IN :Categories3
        ];
        Map<String, Spike_Ticket_Counter__c> thisHourCountersMap = new Map<String, Spike_Ticket_Counter__c>();
        Map<String, Spike_Ticket_Counter__c> lastHourCountersMap = new Map<String, Spike_Ticket_Counter__c>();
        Map<String, Spike_Ticket_Counter__c> previousDaySameHourCountersMap = new Map<String, Spike_Ticket_Counter__c>();
        
        for(Spike_Ticket_Counter__c stc :existingCounters){
            String uniqueKey = stc.Category_1__c + stc.Category_2__c + stc.Category_3__c;
            if(stc.CreatedDate >= thisHour){
                thisHourCountersMap.put(uniqueKey, stc);
            } else if(stc.CreatedDate >= lastHour){
                lastHourCountersMap.put(uniqueKey, stc);
            } else if(stc.CreatedDate >= previousDayLastHour && stc.CreatedDate < previousDayThisHour){
                previousDaySameHourCountersMap.put(uniqueKey, stc);
            }
        }
        List<Spike_Ticket_Counter__c> counters = new List<Spike_Ticket_Counter__c>();
        for(Case c :cases){
            String uniqueKey = c.Category__c + c.Case_SubCategory_1__c + c.Sub_Category2__c;
            Spike_Ticket_Counter__c counter;
            
            if(thisHourCountersMap.containsKey(uniqueKey)){
                counter = thisHourCountersMap.get(uniqueKey);
                counter.This_Hour_Count__c += 1;
            } else {
                counter = new Spike_Ticket_Counter__c(
                    Category_1__c = c.Category__c,
                    Category_2__c = c.Case_SubCategory_1__c,
                    Category_3__c = c.Sub_Category2__c,
                    This_Hour_Count__c = 1
                );
            }
            if(lastHourCountersMap.containsKey(uniqueKey)){
                counter.Last_Hour_Count__c = lastHourCountersMap.get(uniqueKey).This_Hour_Count__c;
            }
            if(previousDaySameHourCountersMap.containsKey(uniqueKey)){
                counter.Same_Hour_Previous_Day_Count__c = previousDaySameHourCountersMap.get(uniqueKey).This_Hour_Count__c;
            }
            counters.add(counter);
        }
        upsert counters;
    }
    
    public static DateTime getLastHourDate(){
        DateTime lastHourDate = DateTime.now().addHours(-1);
        return DateTime.newInstance(lastHourDate.date(), Time.newInstance(lastHourDate.hour(), 0, 0, 0));
    }
    
    public static DateTime getThisHourDate(){
        DateTime lastHourDate = DateTime.now();
        return DateTime.newInstance(lastHourDate.date(), Time.newInstance(lastHourDate.hour(), 0, 0, 0));
    }
    
    public static DateTime getPreviousDayLastHourDate(){
        DateTime lastHourDate = DateTime.now().addHours(-25);
        return DateTime.newInstance(lastHourDate.date(), Time.newInstance(lastHourDate.hour(), 0, 0, 0));
    }
    
    public static DateTime getPreviousDayThisHourDate(){
        DateTime lastHourDate = DateTime.now().addHours(-24);
        return DateTime.newInstance(lastHourDate.date(), Time.newInstance(lastHourDate.hour(), 0, 0, 0));
    }
}