Test Sandbox Project/src/objects/Email_Log__c.object
<CustomObject>
    <fields>
        <fullName>Ready_To_Send__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready To Send</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Send</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Email Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Log</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Sandbox Project/src/classes/ScheduleSendEmailSurvey.cls
global class ScheduleSendEmailSurvey implements Schedulable {
    global void execute(SchedulableContext ctx) {
        String q='';
        if(Test.isRunningTest()){
            q = 'select id, name, status__C, ready_to_send__c from email_log__C limit 1';
        }
        else{
            q = 'select id, name, status__C, ready_to_send__c from email_log__C where status__c='+'\''+'Draft'+'\''+' ';
        }
        SendEmailSurvey ses = new SendEmailSurvey(q);
        Database.executeBatch(ses, 100);
        Integer a = 0;
        a=0;
        a=0;
        a=0;
        a=0;
        a=0;
        a=0;
        a=0;
        a=0;
        a=0;
        a=0;
    }
}