Test Sandbox Project/src/objects/Help_Center__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Id_WP__c</fullName>
        <label>Id WP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Help Center</label>
    <pluralLabel>Help Center</pluralLabel>
</CustomObject>

Test Sandbox Project/src/objects/Help_Center_Article__c.object
<CustomObject>
    <description>Monitor the help center&apos;s created &amp; updated article in wordpress</description>
    <fields>
        <fullName>Id_SF__c</fullName>
        <description>KnowledgeArticleID in Help_Center__kav</description>
        <inlineHelpText>KnowledgeArticleID in Help_Center__kav</inlineHelpText>
        <label>Id_SF</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_WP__c</fullName>
        <label>Id WP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Status__c</fullName>
        <description>Synchronization status</description>
        <inlineHelpText>Synchronization status</inlineHelpText>
        <label>Sync Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Monitor Help Center Article</label>
    <nameField>
        <label>Help Center Article Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monitor Help Center Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Sandbox Project/src/classes/PublicArticleServiceTest.cls
@isTest(seeAllData=true)
public class PublicArticleServiceTest {
    static testmethod void pasTest() {
        Test.startTest();
        
    	String ERROR = 'error';
        
        Help_Center__kav hc = new Help_Center__kav();
        hc.Title = 'Title 1';
        hc.Summary = 'Summary 1';
        hc.UrlName = 'Title-1';
        hc.Body__c = 'Body 1';
        insert hc;
        
        Help_Center_Article__c hca = new Help_Center_Article__c();
        hca.Id_SF__c = 'kA1N00000008ytlKAA';
        hca.Id_WP__c = '202';
        hca.Sync_Status__c = ERROR;
        insert hca;
        
        Help_Center__kav hc2 = new Help_Center__kav();
        hc2.Title = 'Title 2';
        hc2.Summary = 'Summary 2';
        hc2.UrlName = 'Title-2';
        hc2.Body__c = 'Body 2';
        insert hc2;
        
        DescribeSObjectResult describeResultHca = Help_Center_Article__c.getSObjectType().getDescribe();
        List<String> hcaFieldList = new List<String>(describeResultHca.fields.getMap().keySet());
        String hcaFields = String.join(hcaFieldList, ',');
        String qError = 'SELECT ' + hcaFields + ' FROM Help_Center_Article__c LIMIT 1';
        PublicArticleErrorBatch paError = new PublicArticleErrorBatch(qError);
        
        SchedulePublicArticleService spas = new SchedulePublicArticleService();
        spas.execute(null);
        
        SchedulePublicArticleManual.syncManual();
        Test.stopTest();
    }
}